server:
  port: 9000
sa-token:
  # ------- SSO-模式一相关配置  (非模式一不需要配置)
  # cookie:
  # 配置 Cookie 作用域
  # domain: stp.com
  # ------- SSO-模式二相关配置
  sso-server:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    allow-url: "*"
    # ------- SSO-模式三相关配置 （下面的配置在使用SSO模式三时打开）
    # 是否打开模式三
    is-http: true
  sign:
    # API 接口调用秘钥
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
spring:
  application:
    name: mall-sso
  # Redis配置 （SSO模式一和模式二使用Redis来同步会话）
  data:
    redis:
      host: 192.168.117.132
      database: 1
      port: 6379
      password:
      timeout: 3000ms
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
forest:
  # 关闭 forest 请求日志打印
  log-enabled: false
